language: objective-c
osx_image: xcode61
rvm:
  - 2.1.2
install:
  - git clone https://github.com/sttz/install-unity
  #- sudo ./install-unity/install-unity.py --package Unity 5.4.4
  #- sudo ./install-unity/install-unity.py --package Linux --package Windows 5.4.4
script:
  #- ./build.sh
  - mkdir Build
  - touch Build/testfile
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c0435a387948_key -iv $encrypted_c0435a387948_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/Build/ vastan@vastan.net:/home/vastan/public_html/release/development
  on:
    branch: development