language: objective-c
osx_image: xcode61
rvm:
	- 2.1.2
install:
    - curl -o Unity.pkg http://download.unity3d.com/download_unity/3757309da7e7/MacEditorInstaller/Unity-5.2.2f1.pkg
    - sudo installer -dumplog -package Unity.pkg -target /
script:
    - ./build.sh